
#56
name: Java CI with Maven
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: | 
        mvn -B release:update-versions -f ./my-app/pom.xml      #increase patch 
        mvn versions:set -DremoveSnapshot -f ./my-app/pom.xml    #removes -SNAPSHOT
          
          
    - name: Build docker image
      run: |
        docker image build -t mikedgame/github:my-app .
        
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


    - name: Push docker image #f
      run: |
        docker push mikedgame/github:my-app
        
        
    - name: update file and push to remote
      run: |
          cd my-app
          git config --global user.name "MichaelElayev"
          git config --global user.email "michaelelayev@gmail.com@gmail.com"
          git add -A
          git commit -m "version update"
          git push
